### ISSUE TITLE
fix ReferenceError errors for Plyr and mermaid

### ISSUE THREAD

**Issue by IvanVnucec** [forever-jekyll/forever-jekyll#21]
I've forked the repo and make my own page [here](https://ivanvnucec.github.io/).
When I open Mozilla Firefox Developer Tools, I am seeing two errors shown below:
![image](https://user-images.githubusercontent.com/50591550/164712159-364af5b4-0cb2-46d3-8332-2d3e10c9ff9b.png)

**Comment by forever-jekyll** [comment]
I think it had to do something with a bad tag. I've updated and fixed it and those errors should disappear now. Please reopen if it doesn't fix the issue.

**Comment by IvanVnucec** [comment]
> I think it had to do something with a bad tag. I've updated and fixed it and those errors should disappear now. Please reopen if it doesn't fix the issue.

It seems that I don't have rights to reopen issues. Maybe you've changed those repo settings.

**Comment by forever-jekyll** [comment]
Have you updated your repo with the forever-jekyll main branch? A small tag fix in _includes/navigation.html should fix this. I don't see those errors after the tag fix.

**Comment by IvanVnucec** [comment]
I've opened https://forever-jekyll.github.io/ and errors are still here:
![image](https://user-images.githubusercontent.com/50591550/164784230-8e2d7f94-db20-4b86-acee-e1527070609b.png)
